name: Lint

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  run-linters:
    name: Run pylint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install pylint==3.0.3

      - name: Get changed Python files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} -- '*.py')
          else
            git fetch origin main
            changed_files=$(git diff --name-only origin/main -- '*.py')
          fi
          echo "Changed files: $changed_files"
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Run pylint and fail if score < 9.5
        run: |
          if [ -z "$changed_files" ]; then
            echo "No Python files changed. Skipping pylint."
            exit 0
          fi
          pylint_output=$(pylint $changed_files || true)
          echo "$pylint_output"
          score=$(echo "$pylint_output" | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
          result=$(echo "$score < 9.5" | bc)
          if [ "$result" -eq 1 ]; then
            echo "Pylint score is less than 9.5. Merge blocked."
            exit 1
          fi
